control_panel:
  resource: ../../vendor/bolt/core/src/Controller/Backend/
  prefix: '%bolt.backend_url%'
  type: attribute
control_panel_async:
  resource: ../../vendor/bolt/core/src/Controller/Backend/Async
  prefix: '%bolt.backend_url%/async'
  type: attribute
controllers:
  resource: ../../vendor/bolt/core/src/Controller/ImageController.php
  type: attribute
extensions:
  resource: .
  type: bolt_extensions
